import { BaseModel } from "pocketbase";

export interface ISong {
    name: string;

    /**
     * @description The spotify data of the song. Is static and automatically generated on the first recommendation.
     */
    spotify: {
        song: {
            name: string;
            id: string;
            uri: string;
            image: string;
        };
        artist: {
            name: string;
            id: string;
            uri: string;
        }[];
        album: {
            name: string;
            id: string;
            uri: string;
        };
    };

    /**
     * @description Genres are used to describe the song. They can be generated automatically by spotify or manually by users. If they are generated by spotify, ``multiple`` are allowed. If they are generated by users, only ``single`` is allowed.
     */
    genres: string[];
    /**
     * @description tags are used to describe the song, they are generated by users only
     * @example 
     * - "chill"
     * - "party"
     * - "sad"
     * - "happy"
     */
    tags: string[];

    /**
     * @description Specifies the amount of times the song has been recommended.
     * @todo If the user space is implemented, this is referenced by the user. This will create more specific statistics.
     */
    total_recommendations: number;
    /**
     * @description Specifies the amount of times the song has been liked.
     * @todo If the user space is implemented, this is referenced by the user. This will create more specific statistics.
     */
    total_likes: number;
}

export interface SongModel extends ISong, BaseModel {}
