export const genres = {
    "Blues": [
        "Acoustic Blues",
        "Blues Rock",
        "Boogie Woogie",
        "British Blues",
        "Cajun / Zydeco",
        "Chicago-Blues",
        "Classic Female Blues",
        "Country Blues",
        "Delta Blues",
        "Electric Blues",
        "Harmonica Blues",
        "Jazz Blues / Big Band Blues",
        "Louisiana Blues",
        "Piano Blues",
        "Ragtime / Barrelhouse",
        "Rhythm & Blues",
        "Rock & Roll",
        "Soul Blues",
        "Spiritual/Gospel",
        "Texas Blues",
    ],
    "Country": [
        "Alternative Country",
        "Bluegrass",
        "Country Pop",
        "Country Rock",
        "Honky Tonk",
        "Nashville Sound/Traditional Country",
        "Neotraditional/New Country",
        "Outlaw Country",
        "Western Swing",
    ],
    "Dark Wave/Gothic": [
        "Ambient",
        "Batcave",
        "Deathrock",
        "EBM",
        "Electro",
        "Future Pop",
        "Gothic Rock",
        "Industrial",
        "Mittelalterliches",
        "Neofolk",
        "Neoklassik",
        "New Wave",
        "Power Electronics",
        "Synth Pop",
    ],
    "Elektronische Musik": [
        "Acid",
        "Ambient",
        "Berliner Schule",
        "Breakbeat",
        "Chillout",
        "Dancefloor",
        "Dark Ambient",
        "Detroit Techno",
        "Drone",
        "Drum & Bass",
        "Dubstep",
        "Electro",
        "Eurodance",
        "Experimental",
        "Freeform",
        "Freestyle",
        "Goa",
        "Grime",
        "Hard House",
        "Hard Techno",
        "Hardcore",
        "Hardstyle",
        "Industrial",
        "Lounge",
        "Minimal",
        "New Beat",
        "New Rave",
        "Noise",
        "Rave",
        "Speedcore",
        "Techno",
        "Trance",
        "Trip Hop"
    ],
    "Hardcore": [
        "Crustcore",
        "D-Beat",
        "Emocore",
        "Grindcore",
        "Hardcore Punk",
        "Jazzcore",
        "Mathcore",
        "Melodic Hardcore",
        "Metalcore",
        "Noisecore",
        "Post-Hardcore",
        "Power-Violence",
        "Screamo",
        "Sludge",
        "Straight Edge",
        "Thrashcore"
    ],
    "House": [
        "Acid House",
        "Berlin House",
        "Breakbeat",
        "Chicago House",
        "Deephouse",
        "Detroit House",
        "Disco House",
        "Electro House",
        "French House",
        "Garage House",
        "Gospel House",
        "Hip-House",
        "Jersey House",
        "Jungle",
        "Minimal House",
        "Progressive House",
        "Tribal House",
        "Vocal House"
    ],
    "Jazz": [
        "Avantgarde",
        "Bebop",
        "Bigband/Orchester",
        "Bossa Nova",
        "Chicago Jazz",
        "Cool Jazz",
        "Dancefloor / Acid Jazz",
        "Dixieland",
        "Free Jazz",
        "Fusion",
        "Hard Bop",
        "Latin-/Afro-Cuban Jazz",
        "New Orleans Jazz",
        "NuJazz",
        "Ragtime",
        "Soul Jazz",
        "Swing",
        "Symphonic Jazz"
    ],
    "Metal": [
        "Black Metal",
        "Crossover",
        "Death Metal",
        "Doom Metal",
        "Drone",
        "Epic Metal",
        "Folk Metal",
        "Glam Metal",
        "Gothic Metal",
        "Grindcore",
        "Hardrock",
        "Heavy Metal",
        "Industrial Metal",
        "Jazz Metal",
        "Melodic Death Metal",
        "Melodic Metal",
        "Metalcore",
        "Nu Metal",
        "Oriental Metal",
        "Pagan/Viking Metal",
        "Power Metal",
        "Progressive Metal",
        "Sludge",
        "Speed Metal",
        "Stoner Rock/Metal",
        "Symphonic Metal",
        "Thrash Metal"
    ],
    "Pop": [
        "Acapella",
        "Acid",
        "Ambient",
        "Brass",
        "Brit-Pop",
        "Chanson",
        "Country-Pop",
        "Dancefloor",
        "Disco",
        "Dream Pop",
        "Easy Listening",
        "Electro",
        "Eurodance",
        "Folk-Pop",
        "Funk",
        "Gitarrenpop/Hamburger Schule",
        "Hi-NRG",
        "Italo Disco",
        "Italo-Pop",
        "Latin",
        "Neue Deutsche Welle",
        "New Romantic",
        "New Wave",
        "Pop-Klassik",
        "Pop-Rock",
        "Rave/Madchester",
        "Synth Pop"
    ],
    "Punk": [
        "77er Punk",
        "Anarcho-Punk",
        "Art Punk",
        "Cowpunk",
        "Crust",
        "Deutschpunk",
        "Elektropunk",
        "Folk-Punk",
        "Funpunk",
        "Horror-Punk",
        "Melodic Punk",
        "No Wave",
        "Noisepunk",
        "Oi-Punk",
        "Pop Punk",
        "Post-Punk",
        "Psychobilly",
        "Punk Rock",
        "Ska-Punk",
        "Streetpunk",
        "Synth Punk"
    ],
    "Rap/Hip Hop": [
        "Breakdance",
        "Disco Rap",
        "Electro",
        "G-Funk",
        "Gangsta Rap",
        "Miami Bass",
        "Oldschool/Trueschool",
        "Rap Metal",
        "Swingbeat/New Jack Swing",
        "Trip Hop"
    ],
    "Reggae": [
        "Dancehall",
        "Dub",
        "Lovers Rock",
        "Raggamuffin",
        "Reggaeton",
        "Rocksteady/Early Reggae",
        "Roots-Reggae",
        "Skinhead Reggae"
    ],
    "Rock": [
        "AOR",
        "Alternative Rock",
        "Art Rock",
        "Beat",
        "Blues Rock",
        "Celtic Rock",
        "Classic Rock",
        "Country Rock",
        "Crossover",
        "Folk Rock",
        "Funk Rock",
        "Garage Rock",
        "Glamrock",
        "Gothrock",
        "Grunge",
        "Hardrock",
        "Indie Rock",
        "Industrial Rock",
        "Jam Rock",
        "Jazz Rock",
        "Krautrock",
        "Latin Rock",
        "Melodic Rock",
        "Mittelalter Rock",
        "Noise Rock",
        "Nu Metal",
        "Pop-Rock",
        "Post Rock",
        "Power Pop",
        "Progressive Rock",
        "Psychedelic Rock",
        "Rock'n'Roll",
        "Rockabilly",
        "Roots Rock/Americana",
        "Shoegaze",
        "Southern Rock",
        "Space Rock",
        "Stoner Rock",
        "Surf Rock"
    ],
    "Ska": [
        "2Tone",
        "3rd Wave",
        "Jamaican-/Traditional Ska",
        "Postmodern Ska",
        "Rocksteady",
        "Ska-Jazz",
        "Ska-Punk/Skacore"
    ],
    "Soul/R&B": [
        "Funk",
        "Gospel",
        "Modern Soul",
        "Nu Soul",
        "Philly Sound",
        "Psychedelic Soul",
        "Southern Soul/Deep Soul"
    ],
    "Volksmusik/Folklore": [
        "Alpenländische Volksmusik",
        "Asiatische Folklore",
        "Flamenco",
        "Humppa",
        "Irish/Scottish/British Folk",
        "Klezmer",
        "Marschmusik",
        "Mittel-/Westeuropäische Folklore",
        "Mittelalterliches",
        "Neue Volksmusik/Volxmusik",
        "Nordamerikanische Folklore",
        "Osteuropäische Folklore",
        "Shanty/Seemannslieder",
        "Skandivanische Folklore",
        "Südeuropäische Folklore",
        "Volkstümliche Musik/Schlager",
        "Weihnachtslieder",
        "Zigeunermusik"
    ],
    "World Music": [
        "African",
        "Afrobeat",
        "Asian",
        "Calypso",
        "Flamenco",
        "Gospel",
        "Latin",
        "Mambo",
        "Merengue",
        "Rai",
        "Rumba",
        "Salsa",
        "Samba",
        "Soca",
        "Tango",
        "Worldbeat/World Fusion",
        "Zouk"
    ]
}
