export const genres = [
    "Blues",
    "Country",
    "Dark Wave/Gothic",
    "Elektronische Musik",
    "Hardcore",
    "House",
    "Jazz",
    "Metal",
    "Pop",
    "Punk",
    "Rap/Hip Hop",
    "Reggae",
    "Rock",
    "Ska",
    "Soul/R&B",
    "Volksmusik/Folklore",
    "World Music",
]

export const tags = [
    "2Tone",
    "3rd Wave",
    "77er Punk",
    "AOR",
    "Acapella",
    "Acid",
    "Acid House",
    "Acoustic Blues",
    "African",
    "Afrobeat",
    "Alpenländische Volksmusik",
    "Alternative Country",
    "Alternative Rock",
    "Ambient",
    "Anarcho-Punk",
    "Art Punk",
    "Art Rock",
    "Asian",
    "Asiatische Folklore",
    "Avantgarde",
    "Batcave",
    "Beat",
    "Bebop",
    "Berlin House",
    "Berliner Schule",
    "Bigband/Orchester",
    "Black Metal",
    "Bluegrass",
    "Blues Rock",
    "Boogie Woogie",
    "Bossa Nova",
    "Brass",
    "Breakbeat",
    "Breakdance",
    "Brit-Pop",
    "British Blues",
    "Cajun / Zydeco",
    "Calypso",
    "Celtic Rock",
    "Chanson",
    "Chicago House",
    "Chicago Jazz",
    "Chicago-Blues",
    "Chillout",
    "Classic Female Blues",
    "Classic Rock",
    "Cool Jazz",
    "Country Blues",
    "Country Pop",
    "Country Rock",
    "Country-Pop",
    "Cowpunk",
    "Crossover",
    "Crust",
    "Crustcore",
    "D-Beat",
    "Dancefloor",
    "Dancefloor / Acid Jazz",
    "Dancehall",
    "Dark Ambient",
    "Death Metal",
    "Deathrock",
    "Deephouse",
    "Delta Blues",
    "Detroit House",
    "Detroit Techno",
    "Deutschpunk",
    "Disco",
    "Disco House",
    "Disco Rap",
    "Dixieland",
    "Doom Metal",
    "Dream Pop",
    "Drone",
    "Drum & Bass",
    "Dub",
    "Dubstep",
    "EBM",
    "Easy Listening",
    "Electric Blues",
    "Electro",
    "Electro House",
    "Elektropunk",
    "Emocore",
    "Epic Metal",
    "Eurodance",
    "Experimental",
    "Flamenco",
    "Folk Metal",
    "Folk Rock",
    "Folk-Pop",
    "Folk-Punk",
    "Free Jazz",
    "Freeform",
    "Freestyle",
    "French House",
    "Funk",
    "Funk Rock",
    "Funpunk",
    "Fusion",
    "Future Pop",
    "G-Funk",
    "Gangsta Rap",
    "Garage House",
    "Garage Rock",
    "Gitarrenpop/Hamburger Schule",
    "Glam Metal",
    "Glamrock",
    "Goa",
    "Gospel",
    "Gospel House",
    "Gothic Metal",
    "Gothic Rock",
    "Gothrock",
    "Grime",
    "Grindcore",
    "Grunge",
    "Hard Bop",
    "Hard House",
    "Hard Techno",
    "Hardcore",
    "Hardcore Punk",
    "Hardrock",
    "Hardstyle",
    "Harmonica Blues",
    "Heavy Metal",
    "Hi-NRG",
    "Hip-House",
    "Honky Tonk",
    "Horror-Punk",
    "Humppa",
    "Indie Rock",
    "Industrial",
    "Industrial Metal",
    "Industrial Rock",
    "Irish/Scottish/British Folk",
    "Italo Disco",
    "Italo-Pop",
    "Jam Rock",
    "Jamaican-/Traditional Ska",
    "Jazz Blues / Big Band Blues",
    "Jazz Metal",
    "Jazz Rock",
    "Jazzcore",
    "Jersey House",
    "Jungle",
    "Klezmer",
    "Krautrock",
    "Latin",
    "Latin Rock",
    "Latin-/Afro-Cuban Jazz",
    "Louisiana Blues",
    "Lounge",
    "Lovers Rock",
    "Mambo",
    "Marschmusik",
    "Mathcore",
    "Melodic Death Metal",
    "Melodic Hardcore",
    "Melodic Metal",
    "Melodic Punk",
    "Melodic Rock",
    "Merengue",
    "Metalcore",
    "Miami Bass",
    "Minimal",
    "Minimal House",
    "Mittel-/Westeuropäische Folklore",
    "Mittelalter Rock",
    "Mittelalterliches",
    "Modern Soul",
    "Nashville Sound/Traditional Country",
    "Neofolk",
    "Neoklassik",
    "Neotraditional/New Country",
    "Neue Deutsche Welle",
    "Neue Volksmusik/Volxmusik",
    "New Beat",
    "New Orleans Jazz",
    "New Rave",
    "New Romantic",
    "New Wave",
    "No Wave",
    "Noise",
    "Noise Rock",
    "Noisecore",
    "Noisepunk",
    "Nordamerikanische Folklore",
    "Nu Metal",
    "Nu Soul",
    "NuJazz",
    "Oi-Punk",
    "Oldschool/Trueschool",
    "Oriental Metal",
    "Osteuropäische Folklore",
    "Outlaw Country",
    "Pagan/Viking Metal",
    "Philly Sound",
    "Piano Blues",
    "Pop Punk",
    "Pop-Klassik",
    "Pop-Rock",
    "Post Rock",
    "Post-Hardcore",
    "Post-Punk",
    "Postmodern Ska",
    "Power Electronics",
    "Power Metal",
    "Power Pop",
    "Power-Violence",
    "Progressive House",
    "Progressive Metal",
    "Progressive Rock",
    "Psychedelic Rock",
    "Psychedelic Soul",
    "Psychobilly",
    "Punk Rock",
    "Raggamuffin",
    "Ragtime",
    "Ragtime / Barrelhouse",
    "Rai",
    "Rap Metal",
    "Rave",
    "Rave/Madchester",
    "Reggaeton",
    "Rhythm & Blues",
    "Rock & Roll",
    "Rock'n'Roll",
    "Rockabilly",
    "Rocksteady",
    "Rocksteady/Early Reggae",
    "Roots Rock/Americana",
    "Roots-Reggae",
    "Rumba",
    "Salsa",
    "Samba",
    "Screamo",
    "Shanty/Seemannslieder",
    "Shoegaze",
    "Ska-Jazz",
    "Ska-Punk",
    "Ska-Punk/Skacore",
    "Skandivanische Folklore",
    "Skinhead Reggae",
    "Sludge",
    "Soca",
    "Soul Blues",
    "Soul Jazz",
    "Southern Rock",
    "Southern Soul/Deep Soul",
    "Space Rock",
    "Speed Metal",
    "Speedcore",
    "Spiritual/Gospel",
    "Stoner Rock",
    "Stoner Rock/Metal",
    "Straight Edge",
    "Streetpunk",
    "Surf Rock",
    "Swing",
    "Swingbeat/New Jack Swing",
    "Symphonic Jazz",
    "Symphonic Metal",
    "Synth Pop",
    "Synth Punk",
    "Südeuropäische Folklore",
    "Tango",
    "Techno",
    "Texas Blues",
    "Thrash Metal",
    "Thrashcore",
    "Trance",
    "Tribal House",
    "Trip Hop",
    "Vocal House",
    "Volkstümliche Musik/Schlager",
    "Weihnachtslieder",
    "Western Swing",
    "Worldbeat/World Fusion",
    "Zigeunermusik",
    "Zouk"
];
